package servent.messeges;

public enum MessageType {
    PING, PONG, BROADCAST, CAUSAL_BROADCAST, POISON, FACTORIAL_HELP, FACTORIAL_RESULT,TREE_ACCEPT,TREE_REJECT,TREE_QUERY,NODE_DONE,RANGE,RESULT,FACTORIEL_REQUEST,TOKEN
}
